apiVersion: apps/v1
kind: Deployment
metadata:
  name: innovatech-db
  namespace: innovatech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: innovatech-db
  template:
    metadata:
      labels:
        app: innovatech-db
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
      volumes:
        - name: data
          emptyDir: {}
