apiVersion: apps/v1
kind: Deployment
metadata:
  name: innovatech-ventas
  namespace: innovatech
spec:
  replicas: 2
  selector:
    matchLabels:
      app: innovatech-ventas
  template:
    metadata:
      labels:
        app: innovatech-ventas
    spec:
      containers:
        - name: ventas
          image: 519372048065.dkr.ecr.us-east-1.amazonaws.com/innovatech-ventas:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://innovatech-db:3306/ventas_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: OTEL_SDK_DISABLED
              value: "true"
            - name: JAVA_TOOL_OPTIONS
              value: ""
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
