name: cicd_backends

on:
  push:
    branches: ["deploy"]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy Backend vía SSM
        run: |
          aws ssm send-command \
            --instance-ids ${{ secrets.EC2_BACKEND_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --comment "Deploy backend" \
            --parameters 'commands=[
              "cd /home/ec2-user/TU_REPO",
              "git pull origin deploy",

              "docker stop back-despachos || true",
              "docker rm back-despachos || true",
              "docker build -t innovatech-despachos ./back-Despachos_SpringBoot",
              "docker run -d --name back-despachos -p 8080:8080 innovatech-despachos",

              "docker stop back-ventas || true",
              "docker rm back-ventas || true",
              "docker build -t innovatech-ventas ./back-Ventas_SpringBoot",
              "docker run -d --name back-ventas -p 8081:8080 innovatech-ventas"
            ]'
